/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Patient;
import utility.DatabaseConnector;

/**
 *
 * @author danie
 */
public class FormJPanel extends javax.swing.JPanel {
    private ImageIcon pic;
    JPanel bottomJPanel;
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel(JPanel bottomjPanel) {
        this.bottomJPanel = bottomjPanel;
        initComponents();
    }
    public void setPic(ImageIcon pic) { 
        this.pic = pic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JRadioButtonFemale = new javax.swing.JRadioButton();
        JRadioButtonMale = new javax.swing.JRadioButton();
        JLabelName = new javax.swing.JLabel();
        JButtonSubmit = new javax.swing.JButton();
        JRadioButtonOthers = new javax.swing.JRadioButton();
        JTextFieldFirstName = new javax.swing.JTextField();
        JTextFieldLastName = new javax.swing.JTextField();
        JTextFieldAge = new javax.swing.JTextField();
        JLabelGender = new javax.swing.JLabel();
        JImageSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaMessage = new javax.swing.JTextArea();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        formImageHolder = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        buttonGroupGender.add(JRadioButtonFemale);
        JRadioButtonFemale.setText("Female");
        JRadioButtonFemale.setActionCommand("FEMALE");

        buttonGroupGender.add(JRadioButtonMale);
        JRadioButtonMale.setText("Male");
        JRadioButtonMale.setActionCommand("MALE");
        JRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioButtonMaleActionPerformed(evt);
            }
        });

        JLabelName.setText("Last Name");

        JButtonSubmit.setText("Submit");
        JButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSubmitActionPerformed(evt);
            }
        });

        buttonGroupGender.add(JRadioButtonOthers);
        JRadioButtonOthers.setText("Prefer Not To Say");
        JRadioButtonOthers.setActionCommand("OTHERS");

        JTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldFirstNameActionPerformed(evt);
            }
        });

        JTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldLastNameActionPerformed(evt);
            }
        });

        JTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldAgeActionPerformed(evt);
            }
        });

        JLabelGender.setText("Gender");

        JImageSubmit.setText("Upload Image");
        JImageSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JImageSubmitActionPerformed(evt);
            }
        });

        jLabel5.setText("Photo:");

        jLabel1.setText("Patient Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Walk-in", "Appointment", "Emergency", "Home Care" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Age:");

        jLabel4.setText("Email:");

        JTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel6.setText("Message:");

        JTextAreaMessage.setColumns(20);
        JTextAreaMessage.setRows(5);
        jScrollPane1.setViewportView(JTextAreaMessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(JLabelName)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JTextFieldLastName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldFirstName))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelGender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRadioButtonMale)
                            .addComponent(JRadioButtonFemale)
                            .addComponent(JRadioButtonOthers)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JButtonSubmit)
                            .addComponent(JImageSubmit)
                            .addComponent(JDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addGap(18, 18, 18)
                .addComponent(formImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(JTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(JTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRadioButtonMale)
                            .addComponent(JLabelGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRadioButtonFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRadioButtonOthers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JImageSubmit)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonSubmit)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldLastNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JTextFieldLastNameActionPerformed

    private void JRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRadioButtonMaleActionPerformed

    private void JButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSubmitActionPerformed
        // TODO add your handling code here:
        try{
            String firstName = this.JTextFieldFirstName.getText();
            String lastName = this.JTextFieldLastName.getText();
            String age = this.JTextFieldAge.getText();
            String email = this.JTextFieldEmail.getText();
            String message = this.JTextAreaMessage.getText();
            String gender = this.buttonGroupGender.getSelection().getActionCommand();
            String patientType = (String) this.jComboBox1.getSelectedItem();
            java.util.Date selectedDate = this.JDateChooser.getDate();
            String date = new java.text.SimpleDateFormat("yyyy-MM-dd").format(selectedDate);

            if (!firstName.matches("[a-zA-Z ]+") || !lastName.matches("[a-zA-Z ]+")) {
                JOptionPane.showMessageDialog(this, "Name should contain only letters.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!age.matches("\\d+") || Integer.parseInt(age) < 0) {
                JOptionPane.showMessageDialog(this, "Age must be a positive number >= 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(!this._is_valid_email(email) || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Invalidemail format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(message.isEmpty()) { 
                JOptionPane.showMessageDialog(this, "Please Entered Message.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(patientType.isEmpty()) { 
                JOptionPane.showMessageDialog(this, "Please Entered Message.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(date.isEmpty()) { 
                JOptionPane.showMessageDialog(this, "Please Choose The Date.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // This will display the First and Last name
            String displayMessage = "<html>Full Name: " + firstName + " " + lastName +
            "<br>Gender: " + gender +
            "<br>Age: " + age +
            "<br>Email: " + email +
            "<br>Profile Image: </html>";

            JPanel panel = new JPanel();
            JLabel displayMessageLabel = new JLabel(displayMessage) ;
            JLabel imageLabel = new JLabel(this.pic);
            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            panel.add(displayMessageLabel);
            panel.add(imageLabel);

            System.out.println(this.JTextFieldLastName.getText());
            System.out.println(this.JTextFieldLastName.getText());
            System.out.println(this.JTextFieldAge.getText());
            System.out.println(this.JTextFieldEmail.getText());
            System.out.println(this.pic.getImage());
            System.out.println(this.JLabelGender.getText());
            System.out.println(date);

            System.out.println(this.buttonGroupGender.getSelection().getActionCommand());

            JOptionPane.showMessageDialog(this, panel);
            
            // * Passing data as Patient object
            Patient patient = new Patient();
            patient.setFirstName(firstName);
            patient.setLastName(lastName);
            patient.setAge(age);
            patient.setEmail(email);
            patient.setMessage(message);
            patient.setGender(gender);
            patient.setPatientType(patientType);
            patient.setProfilePicture(this.pic);
            patient.setDate(date);
               
            // * Display all the detail of this patient and go to new viewPanel
            DatabaseConnector.addPatient(patient);
            ViewJPanel newViewJPanel = new ViewJPanel(patient);
            this.bottomJPanel.add(newViewJPanel);
            CardLayout layout = (CardLayout) this.bottomJPanel.getLayout();
            layout.next(this.bottomJPanel);
        }
        catch(NullPointerException ne) {
            String errorMessage = "You must enter all fields \n Phone number should be valid \n Email must be valid \n Photo must be choosen \n Patient type must be selected \n Appointment date must be selected.";
            JOptionPane.showMessageDialog(this, errorMessage);
        }
        catch(Exception e) {
            System.out.println("Exception has occurred: ");
            System.out.println(e);
        }
    }//GEN-LAST:event_JButtonSubmitActionPerformed
    
    private boolean _is_valid_email(String email) {
        String regex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@" + 
                       "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(regex);
    }
    
    private void JImageSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JImageSubmitActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        if(file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                Image edited_image = img.getScaledInstance(120, 160, Image.SCALE_SMOOTH);
                if (edited_image != null ){
                    this.setPic(new ImageIcon(edited_image));
                }
                this.formImageHolder.setIcon(this.pic);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please upload image correctly correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_JImageSubmitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldAgeActionPerformed

    private void JTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldEmailActionPerformed

    private void JTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldFirstNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSubmit;
    private com.toedter.calendar.JDateChooser JDateChooser;
    private javax.swing.JButton JImageSubmit;
    private javax.swing.JLabel JLabelGender;
    private javax.swing.JLabel JLabelName;
    private javax.swing.JRadioButton JRadioButtonFemale;
    private javax.swing.JRadioButton JRadioButtonMale;
    private javax.swing.JRadioButton JRadioButtonOthers;
    private javax.swing.JTextArea JTextAreaMessage;
    private javax.swing.JTextField JTextFieldAge;
    private javax.swing.JTextField JTextFieldEmail;
    private javax.swing.JTextField JTextFieldFirstName;
    private javax.swing.JTextField JTextFieldLastName;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JLabel formImageHolder;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
